### ISSUE TITLE
Invalid Reference Format error

### ISSUE THREAD

**Issue by saravanaemis** [jampp/presto-udfs#7]
Hi, I'm trying to test UDF in local before deploying it, And I used docker-compose.template and Make file associated with this repos, But I'm getting below error whilst docker up

Building coordinator
Step 1/7 : ARG VERSION
Step 2/7 : FROM lewuathe/presto-base:${VERSION}
ERROR: Service 'coordinator' failed to build: invalid reference format
make: *** [run-with-logs] Error 1

Could you please help me with this?

**Comment by dpawlow** [comment]
Hi!
This example is a bit old and there have been changes in [Lewuathe's repository](https://github.com/Lewuathe/docker-presto-cluster).
The problem is that now the docker build command needs the version argument to run, for example:

```sh
docker build --build-arg VERSION=${PRESTO_VERSION} -t lewuathe/presto-base:${PRESTO_VERSION} presto-base
```

You can find the updated Lewathe's build command [here](https://github.com/Lewuathe/docker-presto-cluster/blob/02a7118de863f60f84b128f4ce7d7d48b473b37c/Makefile#L7).

However, nowadays there are [PrestoDB](https://github.com/prestodb/docker-images) and [PrestoSQL official images](https://hub.docker.com/r/prestosql/presto), and I think it would be better to use those.

Keep in mind that if you're using PrestoSQL, you'll need to use [this PR's](https://github.com/jampp/presto-udfs/pull/1) branch.

**Comment by dpawlow** [comment]
Updated to work with [TrinoDB](https://github.com/trinodb) (ex PrestoSQL) official docker image.
